name: Build and Test

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build_plugin:
    name: Build and Test
    runs-on: ${{ matrix.os.runner }}

    strategy:
      matrix:
        os:
          - runner: windows-latest
          - runner: ubuntu-latest
          - runner: macos-latest
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          submodules: true # Get JUCE populated

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libcurl4-openssl-dev libwebkit2gtk-4.0-dev libgtk-3-dev \
          xorg-dev

      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -B build

      - name: Build
        working-directory: build
        run: cmake --build . --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: build
        run: ctest
